---
control_plane:
  hosts:
    r[1:3].i.prochowski.pl:
  vars:
    ansible_user: ubuntu

node:
  hosts:
    r[4:5].i.prochowski.pl:
  vars:
    ansible_user: ubuntu

all:
  children:
    control_plane:
    nodes:
  vars:
    ansible_user: ubuntu
