---
- name: Check if a reboot is required.
  become: true
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: reboot_required

- name: Creating fact `reboot_required` based on OS state.
  set_fact:
    reboot_required: "{{ reboot_required.stat.exists }}"
